framework:
    secret: '%env(APP_SECRET)%'
    #csrf_protection: true
    #http_method_override: true

    # Enables session support. Note that the session will ONLY be started if you read or write from it.
    # Remove or comment this section to explicitly disable session support.
    session:
        handler_id: ~
        cookie_secure: auto
        cookie_samesite: lax
        name: SULUSESSID # This avoids conflicts with other applications running on the same domain

    #esi: true
    #fragments: true
    php_errors:
        log: true

    # the IP address (or range) of your proxy
    trusted_proxies: '172.21.0.1/16'
    # trust *all* "X-Forwarded-*" headers
    trusted_headers: [ 'x-forwarded-for', 'x-forwarded-host', 'x-forwarded-proto', 'x-forwarded-port', 'x-forwarded-prefix' ]
