---
name: Alert Composer Audit
on:
  [push]
jobs:
  composer-audit:
    runs-on: ubuntu-latest
    steps:
    - name: Setup PHP with composer v2
      uses: shivammathur/setup-php@v2
      with:
        php-version: '8.1'
        tools: composer:v2

    - name: composer audit
      run: composer audit
